### PR TITLE
Greek pages added

### PR DESCRIPTION
**Pull request by lenasterg**
- 3 greek Pages added: One 1st level with greek typography tests, one level 2 and one level 3
- Lorem ipsub page: Delete 5 paragraphs in order to make the other language's paragraphs more visible
- Lorem ipsub page: Greek paragraph added 
- Greek text added to 'aciform' category
- Greek text added to 'content' tag
- Comments: Rename some "John Doe" commenters to "Γιαννης Τάδε" and add Greek text to comment.

### CODE REVIEW

**Comment by aristath** [comment]
My apologies for not checking this until now, I'll be able to test it tomorrow morning and merge if everything is OK :+1:

**Comment by aristath** [comment]
2 things:

* The `content` tag was renamed to `content περιεχόμενο`. I would have expected a `περιεχόμενο` tag to be added instead of renaming the `content` tag.
* I don't really understand why we'd need new pages to test Greek content... would it not be sufficient to just add Greek characters to the same page that has the `Latin Character Tests` table?

I'm not saying I'm against this btw, but if we add Greek pages then we'd open the door to every language adding extra pages (instead of just checking the characters). It's OK now that only Greek was added, but if next year there's 50 more languages that means that theme-developers (and reviewers) would need to spend significantly more time than necessary, checking pages dedicated to each language.
If the purpose of these extra pages is to test that Greek characters get properly printed and can be viewed without issues, then no extra pages are necessary, we can just build a characters table.
Unless there is a purpose to those pages that I'm not getting?

**Comment by lenasterg** [comment]
Hi @aristath.
Thanks for your review and comments.
All the changes I made were in order to help the theme developer/tester to easily visually locate if and how different Greek characters are displayed in different locations of a theme.

> The content tag was renamed to content περιεχόμενο. I would have expected a περιεχόμενο tag to be added instead of renaming the content tag.
If I have added a tag 'περιεχόμενο' it would be displayed at the end of the tags lists and wouldn't  be 'easy' to the eye to see it and check if there is a font problem

> Why do we need dedicated menus with Greek characters?
We need the Greek page to be displayed in the "short"  and "all pages" menu, so the developer/tester to see possible font mismatch. 

> I don't really understand why we'd need new pages to test Greek content... would it not be sufficient to just add Greek characters to the same page that has the Latin Character Tests table?

No, it is not sufficient, cause not all font types support Greek characters (or Cyrillic, etc) so in many themes, the greek (or other charsets) letters break completely the aesthetic of the theme. 
If different fonts are used from the theme's CSS for the nav items, h1, p, divs, tags, etc, the only way to display possible font problems is by either having a page in Greek with a complete list of typography or adding Greek text into existing page titles, bodies, category names, tags, etc. 
I choose the 1st one option for the pages in order to also have a greek typography page this way. 

Your consideration of the number of possible languages has a point, in the degree, that there are ~34 different charsets of all languages. 
But,  I do think that the theme-unit-test.xml should include one page for each common charset such as Greek, Cyrillic, Chinese, and other common languages and fewer pages/posts in Latin only. 
Greek seemed to me to be a way to start, since it is the language I use and I continues 'bump' on themes that look fine with Latin but terrible with Greek. 


InVariousPlaces
Changes_InPageTitles

**Comment by aristath** [comment]
Thank you @lenasterg for the detailed explanations :+1: 
Merged.

**Pull request merged**
