### PR TITLE
Update themeunittestdata.wordpress.xml

### PR DESCRIPTION
**Pull request by carolinan**
Removes Chip, Emil and Lance as users, and assigns their items to the themedemos user.

### CODE REVIEW

**Comment by christianwach** [comment]
Agree with @joyously - this test will be next-to-useless without multiple users.

**Comment by carolinan** [comment]
I agree.
Personally I'm not sure how to best arrange it.

Just trying to sort out the existing comments and checking what still works and what email adresses we can keep is daunting.

The unit test still lives on the test blog on wordpress.com and the authors need to have access to that blog.
I do know of one more account that we can use as a second author, that the Theme Review Team team leads has access to. 

Currently there is also no template that shows more than one user.

**Comment by joyously** [comment]
Why do they have to be real email addresses? 
I was just referring to the fact that it's nice to have multiple authors (with different choices of display name so that that is tested), for showing in the author archives, and in the author bio. 
Comments should have a range of people also, to test the avatars and site links and whether the commenter is the author of the post.
I think a bunch of this might need to be manually tweaked after import, though. If so, the various page tests should mention it.

**Comment by carolinan** [comment]
Have you read the open issue?

**Pull request merged**
